### PR TITLE
Add prometheus exporter

### PR DESCRIPTION
**Pull request by rossf7**
Towards #4 

Adds a first cut at the exporter.

```bash
go run exporter/main.go

curl -s http://localhost:8000/metrics | grep grid_intensity
# HELP grid_intensity_carbon_actual Actual carbon intensity for the electricity grid in this region.
# TYPE grid_intensity_carbon_actual gauge
grid_intensity_carbon_actual{provider="carbonintensity.org.uk",region="UK"} 157
```

- Currently its just implemented for gridintensity.org.uk as this provider doesn't need an API key.
- It can be tested using curl but it will need a Docker image and manifests for Nomad and Kubernetes to be run in a cluster.

More discussion in https://github.com/thegreenwebfoundation/grid-intensity-go/issues/4#issuecomment-731737516

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Aww dude, this looks sweet! Thanks for working on it.

From what I can read this looks good, and I'm able to run it locally and get the figures at `metrics`, so anyone using Prometheus in the UK would be able to start tracking this at least.

Two things:

### 1. Tests and figuring how to do them

It would be good to have tests or know how to run tests, but:

1. I don't know enough about how to make run tests with Go, or what the idioms are with prometheus - is there a data structure we'd typically check for the existence of specific keys when testing prometheus exporters, or do people test them from the 'outside', and search inside the text output?
2. We have no CI infra setup, and I don't know how complicated it is. Can you let me know what the usual approach is? I'll make an issue for someone to set it up, as with this, an @ofpiyush's there's enough to justify testing now I think.

### 2. Splitting this from the other providers and forecast APIS

I think it's wiser to split this PR from the forecast parts provided by the carbonintensity API, and the electricity map provider, for a few reasons:

1. I'm not sure how much coverage there is for day-ahead, or even hours ahead CO2 figures with electricity map, and it might be worth having a convo about how we ought to proceed in terms of providing a consistent API across providers
2. just having CO2 figures in prometheus is a good start, and already looks usable for test users
3. once this is merged, and a basic CLI is available, I think there's enough here to justify making a release and fleshing out the readme with some instructions.

I think that once there's something available to play with, it'll be easier to find more people contribute to the idea of carbon aware infra

**Comment by rossf7** [comment]
Thanks Chris! :)

> 1. Tests and figuring how to do them

On testing, yes we definitely need coverage. If possible I'd like an integration test but I'm not sure yet how to do that for Nomad. 

For Kubernetes I think we could use KIND (Kubernetes in Docker) https://kind.sigs.k8s.io/. It's a cluster optimized for testing that runs as a Docker container. We could either test just the metrics endpoint or also install Prometheus in the cluster and check the metric exists there.

For which CI we use I don't mind too much. I have some experience with Circle CI but I'm also getting into GitHub Actions a bit recently. @ofpiyush I'm interested to hear your thoughts on this too.

> 2. Splitting this from the other providers and forecast APIS

Yes I think splitting this out makes sense.  I also wondered if a separate repo called `grid-intensity-exporter` might be better. As the exporter needs at least the Prometheus Go client. So the dependencies start to get more complex.

The readme can also be focused on installing the exporter on Nomad and Kubernetes. This is a bit more niche than the API and CLI which have lots of uses. WDYT?

**Comment by ofpiyush** [comment]
> Tests 
I think the simplest setup would be to mock the carbon intensity API server and pretend to be a prometheus collector.

Github actions would totally work for this. 💯 

> I also wondered if a separate repo called grid-intensity-exporter might be better

I like this approach as this repo can remain dependency free.

**Comment by rossf7** [comment]
> Github actions would totally work for this. 💯

Great, I think GitHub actions will work well and will be covered by the free plan.

We could start with using it to run the unit tests here?

> I also wondered if a separate repo called grid-intensity-exporter might be better

> I like this approach as this repo can remain dependency free.

Yes I think a separate repo is better. I'm going to close this for now.

@mrchrisadams Would you be OK to create a `grid-intensity-exporter` repo?

I can then move this there. I'll also have a go at a unit test that mocks the API calls made by the collector. The integration tests will be a bit more complicated and can be done later.

**Comment by mrchrisadams** [comment]
@rossf7 Ross, I've created the repo and added you 👍

**Comment by rossf7** [comment]
@mrchrisadams Gracias amigo! :)

**Pull request closed without merging**
